service: example-serverless-golang-api

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

plugins:
  - serverless-plugin-warmup
custom:
  warmup:
    enabled: true
    concurrency: 5
    prewarm: true
    schedule: rate(5 minutes)
    timeout: 60

functions:
  lambda_1:
    warmup: true
    handler: bin/lambda1/main
    events:
      - http:
          path: lambda1/
          method: get
          cors: true
    request:
      template:
        application/json: '{ "httpMethod" : "$context.httpMethod" }'
  lambda_2:
    warmup: true
    handler: bin/lambda2/main
    events:
      - http:
          path: lambda2/
          method: get
          cors: true
    request:
      template:
        application/json: '{ "httpMethod" : "$context.httpMethod" }'

package:
  exclude:
    - ./**
  include:
    - ./bin/**
