# Set a AWS Lambda execution environment based on Amazon Linux 2
FROM amazonlinux:2
RUN mkdir /var/task
WORKDIR /var/task
RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm